timeout: 5
verbose: yes

/TrustOS
    protocol: limine
    kernel_path: boot():/boot/trustos_kernel
    resolution: 0x0
    module_path: boot():/jarvis_pretrained.bin
    module_cmdline: jarvis-brain
