timeout: 5

/TrustOS Live
    protocol: limine
    resolution: 1920x1080x32
    kernel_path: boot():/boot/trustos_kernel
    cmdline: mode=live jarvis=yes

/TrustOS Live (no JARVIS)
    protocol: limine
    resolution: 1920x1080x32
    kernel_path: boot():/boot/trustos_kernel
    cmdline: mode=live jarvis=no

/TrustOS Install
    protocol: limine
    resolution: 1920x1080x32
    kernel_path: boot():/boot/trustos_kernel
    cmdline: mode=install jarvis=yes
    module_path: boot():/boot/limine/limine-bios.sys
    module_cmdline: limine-bios
    module_path: boot():/EFI/BOOT/BOOTX64.EFI
    module_cmdline: limine-efi
