# Ghidra Python Script - AGX JIT Pipeline Analysis
# Auto-generated by jit_pipeline_mapper.py
# Target: iPhone 11 Pro (A13 / T8030) kernelcache
#
# Usage: Run in Ghidra's Script Manager after loading kernelcache
# @category iOS.Security
# @author jit_pipeline_mapper

from ghidra.program.model.symbol import SourceType
from ghidra.program.model.address import AddressFactory
from ghidra.app.decompiler import DecompInterface

def label_address(addr_int, name):
    """Label an address in Ghidra."""
    addr = currentProgram.getAddressFactory().getDefaultAddressSpace().getAddress(addr_int)
    sym = currentProgram.getSymbolTable()
    sym.createLabel(addr, name, SourceType.USER_DEFINED)
    print(f"Labeled 0x{addr_int:x} as {name}")

def analyze_function(addr_int):
    """Decompile and analyze a function."""
    addr = currentProgram.getAddressFactory().getDefaultAddressSpace().getAddress(addr_int)
    func = getFunctionAt(addr)
    if func is None:
        func = createFunction(addr, None)
    if func:
        decomp = DecompInterface()
        decomp.openProgram(currentProgram)
        result = decomp.decompileFunction(func, 30, monitor)
        if result:
            return result.getDecompiledFunction().getC()
    return None

# ==============================================
# Step 1: Label known AGX/GPU symbols
# ==============================================
print("=" * 60)
print("Labeling AGX/GPU symbols...")
print("=" * 60)


# ==============================================
# Step 2: Search for ExternalMethod dispatch tables
# ==============================================
print("=" * 60)
print("Searching for ExternalMethod dispatch tables...")
print("=" * 60)

# Search for IOExternalMethodDispatch array patterns
# Each entry is 24 bytes: function_ptr(8) + 4x uint32(16)
# Look in __DATA_CONST segment

mem = currentProgram.getMemory()
data_const = None
for block in mem.getBlocks():
    if "__DATA_CONST" in block.getName():
        data_const = block
        break

if data_const:
    print(f"Found __DATA_CONST: {data_const.getStart()} - {data_const.getEnd()}")
    # Automated dispatch table detection would go here
    # For now, manually check addresses from the binary analysis

# ==============================================
# Step 3: Decompile AGX shader compilation path
# ==============================================
print("=" * 60)
print("Analyzing AGX shader compilation path...")
print("=" * 60)

# Key functions to decompile (addresses from symbol analysis):
agx_functions = [
]

for addr, name in agx_functions:
    print(f"\nDecompiling {name} at 0x{addr:x}...")
    c_code = analyze_function(addr)
    if c_code:
        print(c_code[:500])
    else:
        print("  Failed to decompile")

# ==============================================
# Step 4: Trace DART configuration
# ==============================================
print("=" * 60)
print("Tracing DART/IOMMU configuration...")
print("=" * 60)

# Search for references to GPU DART base: 0x231004000
dart_base = 0x231004000
refs = getReferencesTo(currentProgram.getAddressFactory().getDefaultAddressSpace().getAddress(dart_base))
for ref in refs:
    print(f"  DART base ref from: {ref.getFromAddress()}")

# Search for BootROM phys addr: 0x100000000  
bootrom_base = 0x100000000
refs = getReferencesTo(currentProgram.getAddressFactory().getDefaultAddressSpace().getAddress(bootrom_base))
for ref in refs:
    print(f"  BootROM addr ref from: {ref.getFromAddress()}")

print("\n" + "=" * 60)
print("Analysis complete!")
print("=" * 60)
