//! T-RustOs Kernel
//! 
//! Microkernel architecture with capability-based security.
//! Boots via Limine bootloader on UEFI systems.
//!
//! Supported architectures: x86_64, aarch64 (ARM64), riscv64 (RISC-V)

#![no_std]
// #![no_main] — point d'entrée personnalisé au lieu de fn main().
#![no_main]
#![cfg_attr(target_arch = "x86_64", feature(abi_x86_interrupt))]
#![feature(alloc_error_handler)]

// Suppress harmless warnings common in kernel/OS development.
// Many modules define infrastructure for future use or hardware register names.
#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_mut)]
#![allow(unused_parens)]
#![allow(unused_assignments)]
#![allow(unused_doc_comments)]
#![allow(unused_unsafe)]
#![allow(unused_comparisons)]
#![allow(unreachable_code)]
#![allow(unreachable_patterns)]
#![allow(dropping_references)]
#![allow(deprecated)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(nonstandard_style)]
#![allow(static_mut_refs)]
#![allow(asm_sub_register)]
#![allow(private_interfaces)]
#![allow(unexpected_cfgs)]
#![allow(mismatched_lifetime_syntaxes)]
#![allow(unused_must_use)]
#![allow(function_casts_as_integer)]
#![allow(unnecessary_transmutes)]
extern crate alloc;

// Architecture abstraction layer — provides unified interface across all CPUs
pub mod arch;

// Core modules
mod serial;
mod logger;
mod framebuffer;
mod keyboard;
mod shell;
mod ramfs;
mod rtc;
mod mouse;
mod touch;
mod gesture;
mod task;
mod desktop;
mod mobile;
mod visualizer;
mod drone_swarm;
mod disk;
mod network;
mod pci;
mod virtio;
mod virtio_net;
mod virtio_blk;
mod nvme;
mod drivers;
mod netstack;
mod time;
mod rng;
mod file_assoc;
mod accessibility;
mod ui;
mod apps;
mod graphics;
mod icons;
mod browser;
mod game3d; // 3D raycasting FPS game engine
mod chess;   // Chess game engine with AI
mod chess3d; // 3D Matrix-style chess renderer
#[cfg(feature = "emulators")]
mod nes;     // NES emulator (MOS 6502 + 2C02 PPU, iNES ROMs)
#[cfg(feature = "emulators")]
mod gameboy; // Game Boy emulator (Sharp LR35902, MBC1/3/5)
#[cfg(feature = "emulators")]
mod game_lab; // GameLab — real-time Game Boy emulator analysis dashboard
#[cfg(feature = "emulators")]
mod embedded_roms; // ROM data embedded at compile time from kernel/roms/
mod cosmic; // COSMIC-style UI framework (libcosmic-inspired)
mod compositor; // Multi-layer compositor for flicker-free rendering
mod holovolume; // Volumetric ASCII raymarcher - 3D holographic desktop
mod matrix_fast; // Ultra-optimized Matrix rain with Braille sub-pixels
mod formula3d;   // Tsoding-inspired wireframe 3D renderer (perspective projection)
mod gpu_emu;      // Virtual GPU - CPU cores emulating GPU parallelism
// TLS 1.3 pure Rust implementation (no C dependencies)
mod tls13;
// CPU hardware exploitation (TSC, AES-NI, SIMD, SMP)
#[cfg(target_arch = "x86_64")]
mod cpu;
#[cfg(not(target_arch = "x86_64"))]
#[path = "stubs/cpu.rs"]
mod cpu;

// ACPI tables parsing (MADT, FADT, MCFG, HPET)
#[cfg(target_arch = "x86_64")]
mod acpi;
#[cfg(not(target_arch = "x86_64"))]
#[path = "stubs/acpi.rs"]
mod acpi;

// APIC driver (Local APIC + I/O APIC) — replaces legacy PIC for preemptive scheduling
#[cfg(target_arch = "x86_64")]
mod apic;
#[cfg(not(target_arch = "x86_64"))]
#[path = "stubs/apic.rs"]
mod apic;

// New OS infrastructure
mod vfs;
mod process;
mod elf;
mod exec;
mod init;
mod pipe;
#[cfg(target_arch = "x86_64")]
mod gdt;
#[cfg(not(target_arch = "x86_64"))]
#[path = "stubs/gdt.rs"]
mod gdt;

#[cfg(target_arch = "x86_64")]
mod userland;
#[cfg(not(target_arch = "x86_64"))]
#[path = "stubs/userland.rs"]
mod userland;
mod thread;
mod auth;

// Linux distribution manager
mod distro;

// Linux Subsystem (Alpine Linux environment)
mod linux;

// Linux Binary Compatibility Layer (execute real Linux binaries)
mod linux_compat;

// Compression utilities for tar.gz
mod compression;

// Persistence (save downloads to disk)
mod persistence;

// Wayland Compositor (native display server)
mod wayland;

// Binary-to-Rust transpiler (analyze and convert Linux binaries)
mod transpiler;

// Universal RISC-V Translation Layer (run ANY architecture's binaries via RISC-V IR)
mod riscv_translator;

// TrustView — binary analysis engine (ELF parser, disassembler, xrefs)
mod binary_analysis;

// TrustScan — network security scanning toolkit (port scanner, sniffer, vuln scanner)
mod netscan;

// TrustProbe — bare-metal hardware security research toolkit (MMIO, TrustZone, DMA, GPIO)
mod hwscan;

// HWDiag — comprehensive hardware debugging toolkit for PXE boot diagnostics
mod hwdiag;

// Marionet — bare-metal hardware dashboard (full-screen TUI)
mod marionet;

// HTTP Server — embedded web server
mod httpd;

// TrustPkg — package manager
mod trustpkg;

// TrustLab — real-time educational OS introspection laboratory
mod lab_mode;

// TrustWave — real-time WiFi wave analyzer & visualizer
mod wifi_analyzer;

// TrustOS Logo — embedded ARGB bitmap (auto-generated by convert_logo.py)
// In slim builds (no "hires-logo" feature), a stub with no-op draws is used instead.
#[cfg_attr(not(feature = "hires-logo"), path = "logo_bitmap_stub.rs")]
mod logo_bitmap;

// TrustLang — integrated programming language (Rust-like, bytecode VM)
mod trustlang;

// TrustVideo — custom video codec & player (delta+RLE, no external APIs)
mod video;

// Android boot support (boot.img, DTB, PSCI) — aarch64 only
#[cfg(target_arch = "aarch64")]
mod android_boot;
#[cfg(target_arch = "aarch64")]
mod android_main;

// Subsystems
mod memory;
mod interrupts;
mod scheduler;
mod ipc;
mod security;
mod trace;
mod syscall;
mod gui;
mod theme;
mod image;
mod perf;
#[cfg(target_arch = "x86_64")]
mod hypervisor;
#[cfg(not(target_arch = "x86_64"))]
#[path = "stubs/hypervisor.rs"]
mod hypervisor;
mod rasterizer;
mod model_editor;

// Shared math utilities (sin, cos, sqrt, atan2) — centralized
pub mod math;

// Shared buffer drawing helpers (Bresenham, fill_rect, xorshift)
pub mod draw_utils;

// Developer tools (profiler, dmesg, memdbg, devpanel, peek/poke)
mod devtools;

// Hardware debug toolkit (POST codes, backtrace, crash dump, watchdog)
mod debug;

// TrustSynth — polyphonic audio synthesizer engine
mod audio;

// TrustDAW — bare-metal Digital Audio Workstation
mod trustdaw;

// Web Sandbox — capability-gated isolated web execution environment
mod sandbox;

// Kernel signature & proof of authorship
mod signature;
// Ed25519 digital signatures (asymmetric crypto)
pub mod ed25519;

// Synchronization primitives (Redox-inspired)
mod sync;
// POSIX signals
mod signals;
// TTY subsystem (line discipline, sessions)
mod tty;
// Pseudo-terminal (PTY) pairs
mod pty;
// Process tracing (debugging)
mod ptrace;
// Safe user/kernel memory copy
mod usercopy;

// Jarvis Neural Brain — self-hosted tiny transformer for on-device AI
mod jarvis;

// Jarvis Hardware Intelligence — AI-driven hardware awareness and self-optimization
mod jarvis_hw;

use core::panic::PanicInfo;
use core::alloc::Layout;
use limine::request::{
    FramebufferRequest, MemoryMapRequest, HhdmRequest,
    RequestsStartMarker, RequestsEndMarker, ModuleRequest,
    RsdpRequest, SmpRequest, KernelAddressRequest, KernelFileRequest,
    StackSizeRequest,
};
use limine::BaseRevision;

// ============================================================================
// Limine Protocol Requests
// ============================================================================

/// Limine requests start marker
#[used]
#[// SÉCURITÉ : Bloc unsafe — contourne les garanties mémoire de Rust. Vérifier les invariants manuellement.
unsafe(link_section = ".requests_start_marker")]
static _START_MARKER: RequestsStartMarker = RequestsStartMarker::new();

/// Limine base revision - ensures protocol compatibility
#[used]
#[// SÉCURITÉ : Bloc unsafe — contourne les garanties mémoire de Rust. Vérifier les invariants manuellement.
unsafe(link_section = ".requests")]
static BASE_REVISION: BaseRevision = BaseRevision::new();

/// Request framebuffer from Limine for graphics output
#[used]
#[// SÉCURITÉ : Bloc unsafe — contourne les garanties mémoire de Rust. Vérifier les invariants manuellement.
unsafe(link_section = ".requests")]
static FRAMEBUFFER_REQUEST: FramebufferRequest = FramebufferRequest::new();

/// Request memory map from Limine for memory management
#[used]
#[// SÉCURITÉ : Bloc unsafe — contourne les garanties mémoire de Rust. Vérifier les invariants manuellement.
unsafe(link_section = ".requests")]
static MEMORY_MAP_REQUEST: MemoryMapRequest = MemoryMapRequest::new();

/// Request higher half direct map offset for physical memory access
#[used]
#[// SÉCURITÉ : Bloc unsafe — contourne les garanties mémoire de Rust. Vérifier les invariants manuellement.
unsafe(link_section = ".requests")]
static HHDM_REQUEST: HhdmRequest = HhdmRequest::new();

/// Request modules from Limine (Linux kernel and initramfs)
#[used]
#[// SÉCURITÉ : Bloc unsafe — contourne les garanties mémoire de Rust. Vérifier les invariants manuellement.
unsafe(link_section = ".requests")]
static MODULE_REQUEST: ModuleRequest = ModuleRequest::new();

/// Deferred JARVIS brain module data (saved during module scan, written to RamFS after Phase 16)
static mut JARVIS_BRAIN_MODULE: Option<&'static [u8]> = None;

/// Request RSDP (ACPI tables) from Limine
#[used]
#[// SÉCURITÉ : Bloc unsafe — contourne les garanties mémoire de Rust. Vérifier les invariants manuellement.
unsafe(link_section = ".requests")]
static RSDP_REQUEST: RsdpRequest = RsdpRequest::new();

/// Request SMP (multi-core) support from Limine
#[used]
#[// SÉCURITÉ : Bloc unsafe — contourne les garanties mémoire de Rust. Vérifier les invariants manuellement.
unsafe(link_section = ".requests")]
static SMP_REQUEST: SmpRequest = SmpRequest::new();

/// Request kernel address info (needed for virt→phys translation on aarch64)
#[used]
#[// SÉCURITÉ : Bloc unsafe — contourne les garanties mémoire de Rust. Vérifier les invariants manuellement.
unsafe(link_section = ".requests")]
static KERNEL_ADDRESS_REQUEST: KernelAddressRequest = KernelAddressRequest::new();

/// Request kernel file data (for PXE self-replication — serve our own binary)
#[used]
#[// SÉCURITÉ : Bloc unsafe — contourne les garanties mémoire de Rust. Vérifier les invariants manuellement.
unsafe(link_section = ".requests")]
static KERNEL_FILE_REQUEST: KernelFileRequest = KernelFileRequest::new();

/// Request larger stack (512 KB) from Limine to support deep desktop rendering + interrupts
/// 256 KB was insufficient for the desktop's nested draw_background() call chain
/// (4-layer matrix rain × 256 columns × visualizer + drone_swarm per frame)
#[used]
#[// SÉCURITÉ : Bloc unsafe — contourne les garanties mémoire de Rust. Vérifier les invariants manuellement.
unsafe(link_section = ".requests")]
static STACK_SIZE_REQUEST: StackSizeRequest = StackSizeRequest::new().with_size(512 * 1024);

/// Limine requests end marker
#[used]
#[// SÉCURITÉ : Bloc unsafe — contourne les garanties mémoire de Rust. Vérifier les invariants manuellement.
unsafe(link_section = ".requests_end_marker")]
static _END_MARKER: RequestsEndMarker = RequestsEndMarker::new();

// ============================================================================
// Kernel Entry Point
// ============================================================================

// Force the linker to include kmain by creating a static reference to it
#[used]
#[link_section = ".text"]
static KMAIN_REFERENCE: // SÉCURITÉ : Bloc unsafe — contourne les garanties mémoire de Rust. Vérifier les invariants manuellement.
unsafe extern "C" fn() -> ! = kmain;

/// Kernel entry point - called by Limine bootloader
/// 
/// Initializes all kernel subsystems in the correct order:
/// 1. Serial port (for early debug output)
/// 2. Framebuffer console (for screen output)
/// 3. Memory management (heap allocator)
/// 4. Interrupt handling (IDT, PIC)
/// 5. Other subsystems (scheduler, IPC, etc.)
#[no_mangle]
#[link_section = ".text.kmain"]
pub // SÉCURITÉ : Bloc unsafe — contourne les garanties mémoire de Rust. Vérifier les invariants manuellement.
unsafe extern "C" fn kmain() -> ! {
    // Ensure Limine protocol version is supported
    if !BASE_REVISION.is_supported() {
        halt_loop();
    }

    // Phase 0.5: Set up MMIO identity mapping (aarch64 needs Device-nGnRnE attributes)
    // Limine clears TTBR0 and HHDM maps MMIO as Normal Cacheable.
    // We need identity-mapped Device memory for PL011 UART access.
    #[cfg(target_arch = "aarch64")]
    {
        if let Some(ka_resp) = KERNEL_ADDRESS_REQUEST.get_response() {
            crate::arch::platform::boot::setup_mmio_identity_map(
                ka_resp.virtual_base(),
                ka_resp.physical_base(),
            );
        }
        // UART_BASE stays at 0x09000000 (identity-mapped with Device attributes)
    }

    // Phase 0.9: Register kernel file for PXE self-replication
    if let Some(kf_resp) = KERNEL_FILE_REQUEST.get_response() {
        let file = kf_resp.file();
        let ptr = file.addr();
        let size = file.size() as usize;
        if size > 0 {
                        // SÉCURITÉ : Bloc unsafe — contourne les garanties mémoire de Rust. Vérifier les invariants manuellement.
unsafe { jarvis::pxe_replicator::register_kernel_file(ptr, size); }
        }
    }

    // Phase 1: Early init - serial port for debug output
    serial::init();
    debug::checkpoint(debug::POST_SERIAL_INITIALIZE, "Serial port initialized");
    serial_println!("T-RustOs Kernel v0.2.0");
    serial_println!("Limine protocol supported");

    // Phase 1.1: Detect exception level on aarch64
    #[cfg(target_arch = "aarch64")]
    {
        let current_el: u64;
        core::arch::asm!("mrs {}, CurrentEL", out(reg) current_el);
        let el = (current_el >> 2) & 3;
        serial_println!("[AARCH64] CurrentEL = EL{}", el);
        if el == 2 {
            serial_println!("[EL2] *** Hypervisor mode detected! ***");
            serial_println!("[EL2] ARM EL2 MMIO Spy available — use 'hv el2' in shell");
        } else if el == 1 {
            serial_println!("[EL1] Standard kernel mode (no hypervisor)");
        }
    }

    // Phase 2: Initialize framebuffer console
    if let Some(fb_response) = FRAMEBUFFER_REQUEST.get_response() {
        if let Some(fb) = fb_response.framebuffers().next() {
            framebuffer::init(
                fb.addr(),
                fb.width(),
                fb.height(),
                fb.pitch(),
                fb.bpp(),
            );
            serial_println!("Framebuffer: {}x{} @ {:p}", fb.width(), fb.height(), fb.addr());
        }
    }
    
    // === BOOT SPLASH: Draw logo + empty progress bar immediately ===
    framebuffer::initialize_boot_splash();
    
    use framebuffer::BootStatus;

    // Phase 3: Memory management (MUST be before any println! that allocates)
    serial_println!("Initializing memory management...");
    
    let mut heap_initialized = false;
    
    if let Some(mmap_response) = MEMORY_MAP_REQUEST.get_response() {
        let hhdm_offset = HHDM_REQUEST.get_response()
            .map(|r| r.offset())
            .unwrap_or(0);
        
        serial_println!("HHDM offset: {:#x}", hhdm_offset);
        serial_println!("Memory map entries: {}", mmap_response.entries().len());
        
        // Find a usable region for heap (skip first 1MB and kernel/modules)
        let mut usable_for_heap: Option<u64> = None;
        let mut kernel_end: u64 = 0;
        let mut total_phys_memory: u64 = 0;
        
        // Log memory regions and find heap location
        for entry in mmap_response.entries() {
            let kind = // Correspondance de motifs — branchement exhaustif de Rust.
match entry.entry_type {
                limine::memory_map::EntryType::USABLE => "USABLE",
                limine::memory_map::EntryType::RESERVED => "RESERVED",
                limine::memory_map::EntryType::ACPI_RECLAIMABLE => "ACPI_RECLAIM",
                limine::memory_map::EntryType::ACPI_NVS => "ACPI_NVS",
                limine::memory_map::EntryType::BAD_MEMORY => "BAD",
                limine::memory_map::EntryType::BOOTLOADER_RECLAIMABLE => "BOOTLOADER",
                limine::memory_map::EntryType::EXECUTABLE_AND_MODULES => "KERNEL",
                limine::memory_map::EntryType::FRAMEBUFFER => "FRAMEBUFFER",
                _ => "UNKNOWN",
            };
            serial_println!("  {:#012x} - {:#012x} ({:12} bytes) {}", 
                entry.base, 
                entry.base + entry.length,
                entry.length,
                kind
            );
            
            // Store for debug diagnostics
            let type_code = // Correspondance de motifs — branchement exhaustif de Rust.
match entry.entry_type {
                limine::memory_map::EntryType::USABLE => 0u8,
                limine::memory_map::EntryType::RESERVED => 1,
                limine::memory_map::EntryType::ACPI_RECLAIMABLE => 2,
                limine::memory_map::EntryType::ACPI_NVS => 3,
                limine::memory_map::EntryType::BAD_MEMORY => 4,
                limine::memory_map::EntryType::BOOTLOADER_RECLAIMABLE => 5,
                limine::memory_map::EntryType::EXECUTABLE_AND_MODULES => 6,
                limine::memory_map::EntryType::FRAMEBUFFER => 7,
                _ => 0xFF,
            };
            memory::store_memory_region(entry.base, entry.length, type_code);
            
            // Track end of kernel/modules and bootloader reclaimable regions
            if entry.entry_type == limine::memory_map::EntryType::EXECUTABLE_AND_MODULES
                || entry.entry_type == limine::memory_map::EntryType::BOOTLOADER_RECLAIMABLE
            {
                let end = entry.base + entry.length;
                if end > kernel_end {
                    kernel_end = end;
                }
            }
            // Sum only usable memory (not reserved / MMIO / framebuffer)
            if entry.entry_type == limine::memory_map::EntryType::USABLE
                || entry.entry_type == limine::memory_map::EntryType::BOOTLOADER_RECLAIMABLE
                || entry.entry_type == limine::memory_map::EntryType::ACPI_RECLAIMABLE
            {
                total_phys_memory += entry.length;
            }
        }

        // Store total physical memory for later use
        memory::set_total_physical_memory(total_phys_memory);
        serial_println!("[MEM] Total physical memory: {} MB", total_phys_memory / 1024 / 1024);

        // Compute dynamic heap size: 25% of detected RAM, clamped [64 MB, 512 MB]
        let dynamic_heap_size = memory::compute_heap_size(total_phys_memory);
        serial_println!("[HEAP] Dynamic size: {} MB (25% of {} MB RAM)", 
            dynamic_heap_size / 1024 / 1024, total_phys_memory / 1024 / 1024);

        // Align up to 4 KiB
        let align_up = |addr: u64, align: u64| -> u64 {
            if addr % align == 0 { addr } else { addr + (align - (addr % align)) }
        };

        // Find suitable heap region after kernel/modules
        let minimum_heap_base = align_up(core::cmp::max(0x100000, kernel_end), 0x1000);
        for entry in mmap_response.entries() {
            if entry.entry_type != limine::memory_map::EntryType::USABLE {
                continue;
            }
            let region_start = entry.base;
            let region_end = entry.base.saturating_add(entry.length);
            if region_end <= minimum_heap_base {
                continue;
            }
            let heap_start = core::cmp::max(region_start, minimum_heap_base);
            if region_end >= heap_start + dynamic_heap_size as u64 {
                usable_for_heap = Some(heap_start);
                break;
            }
        }

        // If not found, fall back to the largest usable region
        if usable_for_heap.is_none() {
            let mut best_base: u64 = 0;
            let mut best_length: u64 = 0;
            for entry in mmap_response.entries() {
                if entry.entry_type != limine::memory_map::EntryType::USABLE {
                    continue;
                }
                if entry.length > best_length {
                    best_length = entry.length;
                    best_base = entry.base;
                }
            }

            if best_length >= dynamic_heap_size as u64 {
                let mut heap_start = align_up(best_base, 0x1000);
                if heap_start < 0x100000 {
                    heap_start = align_up(0x100000, 0x1000);
                }
                if best_base.saturating_add(best_length) >= heap_start + dynamic_heap_size as u64 {
                    usable_for_heap = Some(heap_start);
                }
            }
        }
        
        // Initialize heap with HHDM (dynamic size)
        if let Some(heap_physical) = usable_for_heap {
            serial_println!("[HEAP] Using mmap region at phys {:#x}, size {} MB", heap_physical, dynamic_heap_size / 1024 / 1024);
            // NOTE: Do NOT use println! here - heap not yet initialized!
            memory::initialize_with_hhdm_dynamic(hhdm_offset, heap_physical, dynamic_heap_size);
            heap_initialized = true;
            serial_println!("[HEAP] Initialized: free={} KB", memory::heap::free() / 1024);
            
            // Initialize frame allocator now that the heap is ready
            // Collect USABLE regions from the memory map
            let usable_regions: alloc::vec::Vec<memory::frame::PhysicalRegion> = mmap_response.entries()
                .iter()
                .filter(|e| e.entry_type == limine::memory_map::EntryType::USABLE)
                .map(|e| memory::frame::PhysicalRegion { base: e.base, length: e.length })
                .collect();
            memory::frame::init(&usable_regions, heap_physical, dynamic_heap_size as u64);
        } else {
            // No region large enough for the computed heap size.
            // Try again with the largest usable region we can find.
            let mut best_base: u64 = 0;
            let mut best_length: u64 = 0;
            for entry in mmap_response.entries() {
                if entry.entry_type != limine::memory_map::EntryType::USABLE && entry.length > best_length {
                    // skip non-usable
                }
                if entry.entry_type == limine::memory_map::EntryType::USABLE && entry.length > best_length {
                    best_length = entry.length;
                    best_base = entry.base;
                }
            }
            
            if best_length >= memory::HEAP_SIZE_MINIMUM as u64 {
                let heap_start2 = align_up(core::cmp::max(best_base, 0x100000), 0x1000);
                let usable_end = best_base.saturating_add(best_length);
                let heap_size2 = core::cmp::min(
                    (usable_end - heap_start2) as usize,
                    dynamic_heap_size,
                );
                let heap_size2 = (heap_size2 / 4096) * 4096; // page-align down
                
                serial_println!("[HEAP] Fallback: using {:#x} size {} MB", heap_start2, heap_size2 / 1024 / 1024);
                memory::initialize_with_hhdm_dynamic(hhdm_offset, heap_start2, heap_size2);
                heap_initialized = true;
                serial_println!("[HEAP] Initialized: free={} KB", memory::heap::free() / 1024);
                
                // Initialize frame allocator
                let usable_regions: alloc::vec::Vec<memory::frame::PhysicalRegion> = mmap_response.entries()
                    .iter()
                    .filter(|e| e.entry_type == limine::memory_map::EntryType::USABLE)
                    .map(|e| memory::frame::PhysicalRegion { base: e.base, length: e.length })
                    .collect();
                memory::frame::init(&usable_regions, heap_start2, heap_size2 as u64);
            } else {
                serial_println!("[HEAP] ERROR: No usable region found for heap!");
            }
        }
    }
    
    if !heap_initialized {
        // Fallback
        serial_println!("[HEAP] Using fallback init");
        memory::init();
    }
    
    // Now that heap is initialized, initialize scrollback buffer (allocates ~3MB)
    serial_println!("[FB] Initializing scrollback buffer...");
    framebuffer::initialize_scrollback();
    
    // Compute SHA-256 of kernel .text section for runtime integrity verification
    signature::initialize_integrity();
    
    // Initialize Ed25519 asymmetric signature (derives keypair from kernel digest)
    signature::initialize_ed25519(&[0x54, 0x72, 0x75, 0x73, 0x74, 0x4f, 0x53]); // "TrustOS" seed
    
    // Now that heap is initialized, show boot banner
    framebuffer::update_boot_splash(0, "Memory management initialized");
    framebuffer::print_boot_status("Memory management initialized", BootStatus::Ok);

    // Phase 3.5: GDT with Ring 0/3 support (x86_64 only)
    #[cfg(target_arch = "x86_64")]
    {
        debug::checkpoint(debug::POST_GDT, "GDT init");
        serial_println!("Initializing GDT with Ring 0/3 support...");
        gdt::init();
        framebuffer::update_boot_splash(1, "GDT initialized (Ring 0/3)");
        framebuffer::print_boot_status("GDT initialized (Ring 0/3)", BootStatus::Ok);
    }
    
    // Phase 3.51: Early interrupts (needed for page fault debugging)
    debug::checkpoint(debug::POST_IDT, "IDT/interrupts init");
    serial_println!("Initializing early interrupts...");
    interrupts::init();
    framebuffer::update_boot_splash(2, "Interrupts initialized");
    framebuffer::print_boot_status("Interrupts (early)", BootStatus::Ok);
    
    // Phase 3.55–3.56: x86_64-specific hardware init (CPU, ACPI, APIC, SMP)
    #[cfg(target_arch = "x86_64")]
    {
        // CPU hardware exploitation (TSC, AES-NI, SIMD, SMP)
        debug::checkpoint(debug::POST_CPU_DETECT, "CPU detection");
        serial_println!("Detecting CPU capabilities...");
        cpu::init();
        framebuffer::update_boot_splash(3, "CPU capabilities detected");
        framebuffer::print_boot_status("CPU capabilities detected", BootStatus::Ok);
        
        // ACPI tables parsing
        debug::checkpoint(debug::POST_ACPI, "ACPI tables parsing");
        serial_println!("Parsing ACPI tables...");
        if let Some(rsdp_response) = RSDP_REQUEST.get_response() {
            let rsdp_pointer = rsdp_response.address();
            serial_println!("[DEBUG] RSDP pointer from Limine: {:#x}", rsdp_pointer as usize);
            if acpi::initialize_direct(rsdp_pointer as u64) {
                if let Some(info) = acpi::get_information() {
                    framebuffer::print_boot_status(&alloc::format!(
                        "ACPI: {} CPUs, {} I/O APICs", 
                        info.cpu_count, info.io_apics.len()
                    ), BootStatus::Ok);
                }
            } else {
                framebuffer::print_boot_status("ACPI init failed", BootStatus::Skip);
            }
        } else {
            framebuffer::print_boot_status("No RSDP from bootloader", BootStatus::Skip);
        }
        
        // APIC initialization — replaces legacy PIC
        debug::checkpoint(debug::POST_APIC, "APIC init");
        serial_println!("Initializing APIC...");
        if apic::init() {
            framebuffer::print_boot_status("APIC initialized (LAPIC + IOAPIC)", BootStatus::Ok);
        } else {
            serial_println!("[APIC] Not available, staying on legacy PIC");
            framebuffer::print_boot_status("APIC not available (legacy PIC)", BootStatus::Skip);
        }

        // HPET initialization — high-precision timer
        if acpi::hpet::init() {
            framebuffer::print_boot_status("HPET initialized", BootStatus::Ok);
        } else {
            framebuffer::print_boot_status("HPET not available", BootStatus::Skip);
        }

        // SMP initialization - Start all CPU cores!
        debug::checkpoint(debug::POST_SMP, "SMP multi-core init");
        serial_println!("Initializing SMP...");
        cpu::smp::init();
        
        if let Some(smp_response) = SMP_REQUEST.get_response() {
            let cpu_count = smp_response.cpus().len();
            serial_println!("[SMP] Found {} CPUs via Limine", cpu_count);
            
            for cpu in smp_response.cpus().iter() {
                if cpu.id != 0 {
                    serial_println!("[SMP] Starting AP {} (LAPIC ID: {})", cpu.id, cpu.lapic_id);
                    cpu.goto_address.write(cpu::smp::ap_entry);
                }
            }
            
            let mut ready_count = 1u32;
            for _ in 0..1000 {
                ready_count = cpu::smp::ready_cpu_count();
                if ready_count >= cpu_count as u32 { break; }
                for _ in 0..10000 { core::hint::spin_loop(); }
            }
            
            serial_println!("[SMP] {} of {} CPUs online", ready_count, cpu_count);
            cpu::smp::set_cpu_count(cpu_count as u32);
            framebuffer::update_boot_splash(4, "SMP multi-core active");
            framebuffer::print_boot_status(&alloc::format!("SMP: {} cores active", ready_count), BootStatus::Ok);
        } else {
            serial_println!("[SMP] No SMP response from bootloader");
            framebuffer::print_boot_status("SMP: single core", BootStatus::Ok);
        }
    }
    
    // Phase 3.6: Paging subsystem
    serial_println!("Initializing paging subsystem...");
    memory::paging::init();  // Saves kernel CR3, enables NX
    framebuffer::update_boot_splash(5, "Paging & memory protection");
    framebuffer::print_boot_status("Paging initialized (NX enabled)", BootStatus::Ok);
    
    // PAT: Enable Write-Combining (WC) — standard GPU driver optimization
    #[cfg(target_arch = "x86_64")]
    let is_vbox = acpi::get_information()
        .map(|info| info.oem_id.trim().eq_ignore_ascii_case("VBOX"))
        .unwrap_or(false);
    #[cfg(not(target_arch = "x86_64"))]
    let is_vbox = false;
    if is_vbox {
        serial_println!("[PAT] Skipping Write-Combining on VirtualBox (VMSVGA compat)");
    } else {
        memory::paging::setup_pat_write_combining();
    }
    
    // Phase 3.7: Userland support (SYSCALL/SYSRET) — x86_64 only
    #[cfg(target_arch = "x86_64")]
    {
        serial_println!("Initializing userland support...");
        userland::initialize_syscall_stack();
        userland::init();
        framebuffer::print_boot_status("Userland support ready", BootStatus::Ok);
    }
    
    // Phase 3.8: Thread subsystem
    serial_println!("Initializing thread subsystem...");
    thread::init();
    framebuffer::update_boot_splash(6, "Thread subsystem ready");
    framebuffer::print_boot_status("Thread subsystem ready", BootStatus::Ok);
    
    // Phase 3.9: Security subsystem (SMEP, SMAP, capabilities)
    serial_println!("Initializing security subsystem...");
    // security::init();  // Disabled for now - CPUID calls may crash on some QEMU
    framebuffer::print_boot_status("Security (basic)", BootStatus::Ok);

    // ── x86_64-specific peripheral init (PS/2, CMOS, PIO-based PCI) ──
    #[cfg(target_arch = "x86_64")]
    {
    // Phase 4: Keyboard driver (interrupts already initialized early)
    keyboard::initialize_i8042();
    serial_println!("Keyboard driver ready");
    framebuffer::update_boot_splash(7, "Keyboard & input devices");
    framebuffer::print_boot_status("Keyboard ready", BootStatus::Ok);

    // Full boot: initialize all subsystems
    // (Set to true only for debugging boot freezes)
    
    // Phase 6: RTC (Real-Time Clock)
    const ENABLE_RTC: bool = true;
    if ENABLE_RTC {
        serial_println!("[RTC] init start");
        if rtc::try_init() {
            framebuffer::print_boot_status("RTC initialized", BootStatus::Ok);
        } else {
            framebuffer::print_boot_status("RTC skipped", BootStatus::Skip);
        }
        serial_println!("[RTC] init done");
    } else {
        framebuffer::print_boot_status("RTC disabled", BootStatus::Skip);
    }

    // Phase 6.1: RNG — detect RDRAND/RDSEED hardware support
    rng::init();
    framebuffer::print_boot_status("RNG (CSPRNG)", BootStatus::Ok);
    
    // Phase 7: Mouse driver
    mouse::init();
    let (fb_width, fb_height) = framebuffer::get_dimensions();
    mouse::set_screen_size(fb_width, fb_height);
    framebuffer::update_boot_splash(8, "Mouse & touch input");
    framebuffer::print_boot_status("Mouse initialized", BootStatus::Ok);
    
    // Phase 7.1: Touch input driver
    touch::init();
    touch::set_screen_size(fb_width, fb_height);
    framebuffer::print_boot_status("Touch input ready", BootStatus::Ok);
    
    // Phase 8-12: Subsystem toggles (enable for full functionality)
    const ENABLE_PCI: bool = true;
        // Constante de compilation — évaluée à la compilation, coût zéro à l'exécution.
const ENABLE_TASKS: bool = true;
        // Constante de compilation — évaluée à la compilation, coût zéro à l'exécution.
const ENABLE_DISK: bool = true;   // Enable for virtio-blk persistence
    const ENABLE_DRIVERS: bool = true;
        // Constante de compilation — évaluée à la compilation, coût zéro à l'exécution.
const ENABLE_NETWORK: bool = true;

    // Phase 8: PCI Bus Enumeration (BEFORE device drivers)
    debug::checkpoint(debug::POST_PCI, "PCI bus enumeration");
    serial_println!("[PHASE] PCI init start");
    framebuffer::print_boot_status("PCI bus scanning...", BootStatus::Info);
    if ENABLE_PCI {
        pci::init();
        framebuffer::update_boot_splash(9, "PCI bus enumeration");
        framebuffer::print_boot_status("PCI bus scanned", BootStatus::Ok);
    } else {
        framebuffer::print_boot_status("PCI disabled", BootStatus::Skip);
    }
    serial_println!("[PHASE] PCI init done");
    
    // Phase 9: Task scheduler
    serial_println!("[PHASE] Task scheduler init start");
    if ENABLE_TASKS {
        task::init();
        scheduler::init();
        framebuffer::update_boot_splash(10, "Task scheduler");
        framebuffer::print_boot_status("Task scheduler ready", BootStatus::Ok);
    } else {
        framebuffer::print_boot_status("Task scheduler disabled", BootStatus::Skip);
    }
    serial_println!("[PHASE] Task scheduler init done");
    
    // Phase 10: Disk I/O
    debug::checkpoint(debug::POST_DISK, "Disk I/O init");
    serial_println!("[PHASE] Disk init start");
    framebuffer::print_boot_status("Disk subsystem...", BootStatus::Info);
    if ENABLE_DISK {
        // Try NVMe first (fastest, real hardware SSD)
        let nvme_devs: alloc::vec::Vec<_> = pci::get_devices().iter()
            .filter(|d| d.class_code == 0x01 && d.subclass == 0x08)
            .cloned()
            .collect();
        
        if !nvme_devs.is_empty() {
                        // Correspondance de motifs — branchement exhaustif de Rust.
match nvme::init(&nvme_devs[0]) {
                Ok(()) => {
                    if let Some((model, _serial, size, lba_sz)) = nvme::get_information() {
                        let mb = (size * lba_sz as u64) / (1024 * 1024);
                        framebuffer::print_boot_status(
                            &alloc::format!("NVMe: {} ({} MB)", model, mb), BootStatus::Ok);
                    }
                }
                Err(e) => {
                    crate::log_warn!("[DISK] NVMe init failed: {}", e);
                }
            }
        }
        
        // Try virtio-blk (for QEMU guests without NVMe)
        if !nvme::is_initialized() {
            let block_devs: alloc::vec::Vec<_> = pci::get_devices().iter()
                .filter(|d| d.vendor_id == 0x1AF4 && d.device_id == 0x1001)
                .cloned()
                .collect();
            
            if !block_devs.is_empty() {
                if let Err(e) = virtio_blk::init(&block_devs[0]) {
                    crate::log_warn!("[DISK] virtio-blk init failed: {}", e);
                    disk::init();
                } else {
                    framebuffer::print_boot_status(&alloc::format!("virtio-blk: {} MB storage", 
                        (virtio_blk::capacity() * 512) / (1024 * 1024)), BootStatus::Ok);
                }
            } else {
                // No NVMe, no virtio-blk → RAM disk
                disk::init();
            }
        }
        
        if disk::is_available() || virtio_blk::is_initialized() || nvme::is_initialized() {
            framebuffer::print_boot_status("Disk driver ready", BootStatus::Ok);
        } else {
            framebuffer::print_boot_status("No disk detected", BootStatus::Skip);
        }
    } else {
        framebuffer::print_boot_status("Disk disabled", BootStatus::Skip);
    }
    serial_println!("[PHASE] Disk init done");
    
    // Phase 11: Driver Framework
    serial_println!("[PHASE] Driver framework init start");
    if ENABLE_DRIVERS {
        drivers::init();
        // Probe storage controllers (AHCI, IDE)
        drivers::probe_storage();
        framebuffer::update_boot_splash(12, "Driver framework");
        framebuffer::print_boot_status("Driver framework initialized", BootStatus::Ok);
        if drivers::has_storage() {
            framebuffer::print_boot_status("Persistent storage detected", BootStatus::Ok);
        }
    } else {
        framebuffer::print_boot_status("Driver framework disabled", BootStatus::Skip);
    }
    serial_println!("[PHASE] Driver framework init done");
    
    // Phase 11b: VirtIO GPU
    serial_println!("[PHASE] VirtIO GPU init start");
    framebuffer::print_boot_status("VirtIO GPU...", BootStatus::Info);
    drivers::virtio_gpu::initialize_from_pci().ok();
    if drivers::virtio_gpu::is_available() {
        framebuffer::print_boot_status(&alloc::format!("VirtIO GPU: {}", drivers::virtio_gpu::information_string()), BootStatus::Ok);
    } else {
        framebuffer::print_boot_status("VirtIO GPU: not found (fallback framebuffer)", BootStatus::Skip);
    }
    serial_println!("[PHASE] VirtIO GPU init done");
    
    // Phase 11c: AMD GPU (native hardware driver)
    serial_println!("[PHASE] AMD GPU init start");
    framebuffer::print_boot_status("AMD GPU...", BootStatus::Info);
    drivers::amdgpu::init();
    if drivers::amdgpu::is_detected() {
        framebuffer::print_boot_status(&alloc::format!("AMD GPU: {}", drivers::amdgpu::summary()), BootStatus::Ok);
    } else {
        framebuffer::print_boot_status("AMD GPU: not found (VM or non-AMD)", BootStatus::Skip);
    }
    serial_println!("[PHASE] AMD GPU init done");
    
    // Phase 11d: NVIDIA GPU (NV50/Tesla — ThinkPad T61)
    serial_println!("[PHASE] NVIDIA GPU init start");
    framebuffer::print_boot_status("NVIDIA GPU...", BootStatus::Info);
    drivers::nvidia::init();
    if drivers::nvidia::is_detected() {
        framebuffer::print_boot_status(&alloc::format!("NVIDIA GPU: {}", drivers::nvidia::summary()), BootStatus::Ok);
    } else {
        framebuffer::print_boot_status("NVIDIA GPU: not found", BootStatus::Skip);
    }
    serial_println!("[PHASE] NVIDIA GPU init done");
    
    // Remap framebuffer as Write-Combining for faster MMIO writes
    // Skip on VirtualBox: VMSVGA dirty-tracking breaks with WC pages
    if !is_vbox {
        let framebuffer_address = framebuffer::FRAMEBUFFER_ADDRESS.load(core::sync::atomic::Ordering::SeqCst);
        let fb_w = framebuffer::FRAMEBUFFER_WIDTH.load(core::sync::atomic::Ordering::SeqCst) as usize;
        let fb_h = framebuffer::FRAMEBUFFER_HEIGHT.load(core::sync::atomic::Ordering::SeqCst) as usize;
        if !framebuffer_address.is_null() && fb_w > 0 && fb_h > 0 {
            let framebuffer_size = fb_w * fb_h * 4;
            let _ = memory::paging::remap_region_write_combining(framebuffer_address as u64, framebuffer_size);
        }
    } else {
        serial_println!("[PAT] Skipping framebuffer WC remap on VirtualBox");
    }
    
    // Phase 12: Network (with universal driver system)
    debug::checkpoint(debug::POST_NETWORK, "Network init");
    serial_println!("[PHASE] Network init start");
    framebuffer::print_boot_status("Network subsystem...", BootStatus::Info);
    if ENABLE_NETWORK {
        network::init();
        if network::is_available() {
            // Display detected platform
            let platform = network::get_platform();
            framebuffer::print_boot_status(&alloc::format!("Platform: {}", platform), BootStatus::Info);
            
            // Auto-probe network drivers in two passes:
            // Pass 1: WiFi — DEFERRED to first `wifi` command (map_bar0 can triple-fault on bare metal)
            // Pass 2: Ethernet (probe + start)
            framebuffer::print_boot_status("PCI scan...", BootStatus::Info);
            let devs = pci::find_by_class(pci::class::NETWORK);
            framebuffer::print_boot_status(&alloc::format!("Found {} network devices", devs.len()), BootStatus::Info);
            
            // WiFi: just remember PCI info, don't touch hardware yet
            // The actual probe (map_bar0 + MMIO) happens on first `wifi` shell command
            for dev in &devs {
                if dev.vendor_id == 0x8086 
                    && (dev.subclass == 0x80 || dev.class_code == 0x0D 
                        || drivers::net::iwl4965::IWL4965_DEVICE_IDS.contains(&dev.device_id))
                {
                    framebuffer::print_boot_status(
                        &alloc::format!("WiFi detected: {:04X}:{:04X} (deferred)", dev.vendor_id, dev.device_id),
                        BootStatus::Info);
                    // Store PCI location for lazy probe later
                    drivers::net::wifi::set_deferred_pci(dev.bus, dev.device, dev.function);
                }
            }
            
            // Pass 2: Probe Ethernet driver (first match only)
            println!("  Ethernet probe starting...");
            framebuffer::print_boot_status("Ethernet probe...", BootStatus::Info);
            for dev in &devs {
                if drivers::net::probe_device(dev) {
                    network::update_mac_from_driver();
                    let driver_name = if dev.vendor_id == 0x1AF4 { "virtio-net" } 
                        else if dev.vendor_id == 0x8086 { "e1000" }
                        else if dev.vendor_id == 0x10EC { "rtl8139" }
                        else { "unknown" };
                    framebuffer::print_boot_status(&alloc::format!("Network driver: {}", driver_name), BootStatus::Ok);
                    break;
                }
            }

            // Fallback: init legacy virtio-net if no active universal driver
            if !drivers::net::has_driver() && !crate::virtio_net::is_initialized() {
                if let Some(dev) = devs.iter().find(|d| d.vendor_id == 0x1AF4) {
                    if let Err(e) = crate::virtio_net::init(dev) {
                        crate::log_warn!("[NET] Legacy virtio-net init failed: {}", e);
                    } else {
                        network::update_mac_from_driver();
                        framebuffer::print_boot_status("Network driver: virtio-net (legacy)", BootStatus::Ok);
                    }
                }
            }
            
            framebuffer::update_boot_splash(14, "Network stack ready");
            framebuffer::print_boot_status("Network ready", BootStatus::Ok);
            
            // Start network stack
            netstack::dhcp::start();
            netstack::ipv6::init();
            netstack::tcp::initialize_isn_secret();
        }
    } else {
        framebuffer::print_boot_status("Network disabled", BootStatus::Skip);
    }
    serial_println!("[PHASE] Network init done");
    } // end #[cfg(target_arch = "x86_64")] block

    // ── aarch64: skip x86 peripherals, use minimal boot ──
    #[cfg(target_arch = "aarch64")]
    {
        serial_println!("[AARCH64] Skipping x86 peripherals (keyboard, RTC, mouse, PCI)");
        framebuffer::print_boot_status("Keyboard: N/A (serial)", BootStatus::Skip);
        framebuffer::print_boot_status("RTC: N/A", BootStatus::Skip);
        framebuffer::print_boot_status("PCI: N/A (ECAM not yet)", BootStatus::Skip);
        framebuffer::print_boot_status("Network: N/A", BootStatus::Skip);
    }

    // ========================================================================
    // Phase 12: VFS Initialization
    // ========================================================================
    debug::checkpoint(debug::POST_VFS, "VFS init");
    serial_println!("[PHASE] VFS init start");
    vfs::init();
    serial_println!("[PHASE] VFS init done");
    framebuffer::update_boot_splash(15, "Virtual filesystem (VFS)");
    framebuffer::print_boot_status("Virtual filesystem ready", BootStatus::Ok);
    
    // ========================================================================
    // Phase 12a: Linux Subsystem (TSL) - x86_64 only (uses hypervisor)
    // ========================================================================
    #[cfg(target_arch = "x86_64")]
    {
        serial_println!("[PHASE] Linux Subsystem init start");
        if let Some(module_response) = MODULE_REQUEST.get_response() {
            let modules = module_response.modules();
            serial_println!("[TSL] Found {} boot modules", modules.len());
            
            let mut kernel_data: Option<&'static [u8]> = None;
            let mut initramfs_data: Option<&'static [u8]> = None;
            
            for module in modules {
                let cmdline_bytes = module.cmdline();
                let cmdline = core::str::from_utf8(cmdline_bytes).unwrap_or("unknown");
                let path = module.path().to_str().unwrap_or("unknown");
                let addr = module.addr();
                let size = module.size() as usize;
                
                serial_println!("[TSL] Module: {} ({}), {} bytes at {:p}", 
                    cmdline, path, size, addr);
                
                let data = // SÉCURITÉ : Bloc unsafe — contourne les garanties mémoire de Rust. Vérifier les invariants manuellement.
unsafe { core::slice::from_raw_parts(addr, size) };
                
                if cmdline.contains("linux-kernel") || path.contains("bzImage") {
                    kernel_data = Some(data);
                    serial_println!("[TSL] Linux kernel loaded: {} bytes", size);
                } else if cmdline.contains("linux-initramfs") || path.contains("initramfs") {
                    initramfs_data = Some(data);
                    serial_println!("[TSL] Initramfs loaded: {} bytes", size);
                } else if cmdline.contains("jarvis-brain") || path.contains("jarvis_pretrained") {
                    // Save pointer — RamFS not yet initialized, will copy after Phase 16
                    serial_println!("[JARVIS] Boot module: {} bytes brain weights (deferred to RamFS)", size);
                                        // SÉCURITÉ : Bloc unsafe — contourne les garanties mémoire de Rust. Vérifier les invariants manuellement.
unsafe { JARVIS_BRAIN_MODULE = Some(data); }
                } else if cmdline.contains("iwlwifi") || path.contains("iwlwifi") || path.contains(".ucode") {
                    // WiFi firmware module — store for driver initialization
                    serial_println!("[WIFI] Firmware module: {} bytes at {:p}", size, addr);
                    let fw_vec = alloc::vec::Vec::from(data);
                    drivers::net::iwl4965::set_firmware_data(&fw_vec);
                }
            }
            
            if let (Some(kernel), Some(initramfs)) = (kernel_data, initramfs_data) {
                hypervisor::linux_subsystem::subsystem().set_embedded_images(kernel, initramfs);
                framebuffer::print_boot_status("Linux Subsystem (TSL) ready", BootStatus::Ok);
            } else {
                framebuffer::print_boot_status("Linux Subsystem (partial)", BootStatus::Skip);
            }
        } else {
            framebuffer::print_boot_status("Linux Subsystem (no modules)", BootStatus::Skip);
        }
        serial_println!("[PHASE] Linux Subsystem init done");
    }
    
    // ========================================================================
    // Phase 12b: File Associations
    // ========================================================================
    file_assoc::init();
    framebuffer::print_boot_status("File associations ready", BootStatus::Ok);
    
    // ========================================================================
    // Phase 13: Process Manager
    // ========================================================================
    debug::checkpoint(debug::POST_PROCESS, "Process manager init");
    serial_println!("[PHASE] Process manager init start");
    process::init();
    framebuffer::update_boot_splash(17, "Process manager");
    framebuffer::print_boot_status("Process manager ready", BootStatus::Ok);
    serial_println!("[PHASE] Process manager init done");
    
    // ========================================================================
    // Phase 14: Authentication System
    // ========================================================================
    serial_println!("[PHASE] Auth system init");
    auth::init();
    auth::create_etc_files();
    framebuffer::update_boot_splash(18, "Authentication system");
    framebuffer::print_boot_status("Authentication ready", BootStatus::Ok);
    
    // Phase 14b: TTY / PTY subsystem
    serial_println!("[PHASE] TTY/PTY init");
    tty::init();
    pty::init();
    framebuffer::print_boot_status("TTY/PTY subsystem ready", BootStatus::Ok);
    
    // ========================================================================
    // Phase 15: Init Process (PID 1)
    // ========================================================================
    serial_println!("[PHASE] Init process start");
    init::start();
    framebuffer::print_boot_status("Init process started (PID 1)", BootStatus::Ok);
    serial_println!("[PHASE] Init process done");
    
    // ========================================================================
    // Phase 16: RAM Filesystem
    // ========================================================================
    serial_println!("[PHASE] RAM filesystem init");
    ramfs::init();
    framebuffer::update_boot_splash(19, "RAM filesystem");
    // Create standard directories
    ramfs::with_filesystem(|fs| {
        let _ = fs.mkdir("/tmp");
        let _ = fs.mkdir("/var");
        let _ = fs.mkdir("/home");
        let _ = fs.mkdir("/bin");
        let _ = fs.mkdir("/usr");
        let _ = fs.mkdir("/etc");
    });

    // Copy deferred JARVIS brain module into RamFS (saved during Phase 12a)
    if let Some(brain_data) = // SÉCURITÉ : Bloc unsafe — contourne les garanties mémoire de Rust. Vérifier les invariants manuellement.
unsafe { JARVIS_BRAIN_MODULE.take() } {
        serial_println!("[JARVIS] Copying {} KB brain weights to RamFS...", brain_data.len() / 1024);
        ramfs::with_filesystem(|fs| {
            let _ = fs.mkdir("/jarvis");
        });
        ramfs::with_filesystem(|fs| {
            let _ = fs.touch("/jarvis/weights.bin");
                        // Correspondance de motifs — branchement exhaustif de Rust.
match fs.write_file("/jarvis/weights.bin", brain_data) {
                Ok(_) => serial_println!("[JARVIS] Brain weights cached to /jarvis/weights.bin ({} KB)", brain_data.len() / 1024),
                Err(_) => serial_println!("[JARVIS] WARNING: Failed to cache brain to RamFS"),
            }
        });
    }

    framebuffer::print_boot_status("RAM filesystem ready", BootStatus::Ok);

    // Load user/group data from /etc files (if persisted from previous boot)
    auth::load_from_filesystem();

    // ========================================================================
    // Phase 17: Persistence System
    // ========================================================================
    serial_println!("[PHASE] Persistence init");
    persistence::init();
    framebuffer::update_boot_splash(20, "Persistence layer");
    framebuffer::print_boot_status("Persistence system ready", BootStatus::Ok);

    // ========================================================================
    // Phase 18: Web Sandbox
    // ========================================================================
    serial_println!("[PHASE] Web Sandbox init");
    sandbox::init();
    framebuffer::print_boot_status("Web Sandbox ready", BootStatus::Ok);

    // Phase 18b: Container Daemon (auto-starts default web container)
    serial_println!("[PHASE] Container daemon boot");
    sandbox::container::boot_daemon();
    framebuffer::update_boot_splash(21, "System ready!");
    framebuffer::print_boot_status("Container daemon ready", BootStatus::Ok);

    // === BOOT SPLASH: Fade out before transitioning to shell ===
    // Brief pause to show 100% completion
    for _ in 0..5_000_000u64 { core::hint::spin_loop(); }
    framebuffer::fade_out_splash();

    // Final boot summary
    println!();
    framebuffer::draw_separator(framebuffer::get_cursor().1 as u32 * 16, framebuffer::COLOR_GREEN);
    println!();
    println_color!(framebuffer::COLOR_BRIGHT_GREEN, "  System ready - TRust-OS v0.2.0");
    println_color!(framebuffer::COLOR_GREEN, "  Type 'desktop' to launch the desktop, or use shell commands.");
    println!();

    // Check for saved data and ask user
    if persistence::is_available() {
        persistence::prompt_restore();
    }

    // Auto-login as root for now (development mode)
    auth::auto_login_root();

    // Marionet: auto-dump hardware report to USB if a key is plugged in
    marionet::autodump::boot_autodump();

    // Run crypto self-tests at startup
    serial_println!("[BOOT] Running crypto self-tests...");
    tls13::crypto::run_self_tests();
    serial_println!("[BOOT] Crypto self-tests complete");

    // Start shell (runs forever)
    debug::checkpoint(debug::POST_SHELL_READY, "Shell ready — boot complete");
    serial_println!("Starting shell...");
    shell::run();
}

// ============================================================================
// Core Functions
// ============================================================================

/// Halt the CPU in an infinite loop
/// Used when kernel cannot continue or has nothing to do
fn halt_loop() -> ! {
    arch::halt_loop()
}

#[alloc_error_handler]
fn allocator_error(layout: Layout) -> ! {
    serial_println!("\n!!! ALLOC ERROR !!!");
    serial_println!("layout: size={}, align={}", layout.size(), layout.align());
    if framebuffer::is_initialized() {
        framebuffer::set_fg_color(framebuffer::COLOR_RED);
        println!("\n!!! ALLOC ERROR !!!");
        println!("layout: size={}, align={}", layout.size(), layout.align());
    }
    halt_loop();
}

/// Panic handler - called on unrecoverable errors
#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    // POST code 0xFF = panic
    debug::post_code(debug::POST_PANIC);
    
    // Full crash dump to serial (registers, backtrace, stack, checkpoints)
    debug::panic_dump();
    
    // Also print the panic message itself
    serial_println!("\n!!! KERNEL PANIC !!!");
    serial_println!("{}", info);
    
    // Try framebuffer if available
    if framebuffer::is_initialized() {
        framebuffer::set_fg_color(framebuffer::COLOR_RED);
        println!("\n!!! KERNEL PANIC !!!");
        println!("{}", info);
        framebuffer::set_fg_color(0xFFAAAAAA);
        println!("Full crash dump sent to serial port (115200 8N1).");
        println!("Connect serial cable and reboot to capture output.");
        // Show backtrace on screen too
        let bt = debug::format_backtrace(8);
        for line in &bt {
            println!("{}", line);
        }
    }
    
    halt_loop();
}
