


use alloc::string::String;
use alloc::vec::Vec;
use alloc::vec;
use alloc::format;

use super::{Dc, Anj, BinaryType, gty, Register, Operand};


pub struct Transpiler {
    pub instructions: Vec<Dc>,
    pub apd: Vec<Anj>,
    hws: Option<u64>,
    hwv: Option<u64>,
    hye: Option<u64>,
    hww: Option<u64>,
}

impl Transpiler {
    pub fn new(instructions: Vec<Dc>) -> Self {
        Self {
            instructions,
            apd: Vec::new(),
            hws: None,
            hwv: None,
            hye: None,
            hww: None,
        }
    }
    
    
    pub fn qie(&mut self) {
        self.hws = None;
        self.hwv = None;
        self.hye = None;
        self.hww = None;
        
        for fi in &self.instructions {
            
            if fi.bes == "mov" && fi.bvr.len() >= 2 {
                if let (Operand::Register(reg), Operand::Acf(ap)) = (&fi.bvr[0], &fi.bvr[1]) {
                    match reg {
                        Register::Me | Register::Abh => self.hws = Some(*ap as u64),
                        Register::Alq => self.hwv = Some(*ap as u64),
                        Register::Alt => self.hye = Some(*ap as u64),
                        Register::Alr => self.hww = Some(*ap as u64),
                        _ => {}
                    }
                }
            }
            
            
            if fi.bes == "xor" && fi.bvr.len() >= 2 {
                if let (Operand::Register(aqh), Operand::Register(uv)) = (&fi.bvr[0], &fi.bvr[1]) {
                    if aqh == uv {
                        match aqh {
                            Register::Me | Register::Abh => self.hws = Some(0),
                            Register::Alq => self.hwv = Some(0),
                            Register::Alt => self.hye = Some(0),
                            Register::Alr => self.hww = Some(0),
                            _ => {}
                        }
                    }
                }
            }
            
            
            if fi.bes == "syscall" {
                if let Some(num) = self.hws {
                    let mut n = Vec::new();
                    if let Some(p) = self.hwv { n.push(p); }
                    if let Some(p) = self.hye { n.push(p); }
                    if let Some(p) = self.hww { n.push(p); }
                    
                    self.apd.push(Anj {
                        re: fi.re,
                        aqb: num,
                        j: gty(num),
                        n,
                    });
                }
            }
        }
    }
    
    
    pub fn rwn(&self) -> BinaryType {
        if self.apd.is_empty() {
            return BinaryType::F;
        }
        
        
        if self.apd.len() == 1 {
            let jt = &self.apd[0];
            if jt.j == "exit" || jt.j == "exit_group" {
                return BinaryType::Buq;
            }
        }
        
        
        let prd: Vec<&str> = self.apd.iter().map(|e| e.j).collect();
        
        if prd.contains(&"getcwd") {
            return BinaryType::Bps;
        }
        
        if prd.contains(&"uname") {
            return BinaryType::Ra;
        }
        
        
        for jt in &self.apd {
            if jt.j == "write" && jt.n.len() > 0 && jt.n[0] == 1 {
                return BinaryType::Bfs;
            }
        }
        
        BinaryType::F
    }
    
    
    pub fn tcc(&self, kdi: BinaryType, f: &[u8]) -> String {
        let mut aj = String::new();
        
        aj.t("// Auto-generated by TrustOS Binary Transpiler\n");
        aj.t("// This code is functionally equivalent to the original binary\n\n");
        aj.t("#![no_std]\n#![no_main]\n\n");
        
        match kdi {
            BinaryType::Buq => {
                self.tcq(&mut aj);
            }
            BinaryType::Bfs => {
                self.tcb(&mut aj, f);
            }
            BinaryType::Bps => {
                self.tcj(&mut aj);
            }
            BinaryType::Ra => {
                self.tcr(&mut aj);
            }
            BinaryType::Cfb => {
                self.tcf(&mut aj);
            }
            BinaryType::Bzh => {
                self.tbx(&mut aj);
            }
            BinaryType::Cgx => {
                self.tcg(&mut aj);
            }
            BinaryType::F => {
                self.tcd(&mut aj);
            }
        }
        
        aj
    }
    
    fn tcq(&self, aj: &mut String) {
        let nz = if let Some(jt) = self.apd.fv() {
            if jt.n.len() > 0 { jt.n[0] as i32 } else { 0 }
        } else {
            0
        };
        
        aj.t("/// Transpiled: exit program\n");
        aj.t("/// Original: mov rax, 60; mov rdi, ");
        aj.t(&format!("{}; syscall\n", nz));
        aj.t("\n");
        aj.t("use trustos_rt::prelude::*;\n\n");
        aj.t("#[no_mangle]\n");
        aj.t("pub extern \"C\" fn _start() -> ! {\n");
        aj.t(&format!("    sys_exit({});\n", nz));
        aj.t("}\n\n");
        aj.t("// TrustOS native implementation\n");
        aj.t("mod trustos_rt {\n");
        aj.t("    pub mod prelude {\n");
        aj.t("        pub fn sys_exit(code: i32) -> ! {\n");
        aj.t("            // Call TrustOS exit syscall\n");
        aj.t("            unsafe {\n");
        aj.t("                core::arch::asm!(\n");
        aj.t("                    \"syscall\",\n");
        aj.t("                    in(\"rax\") 60u64,  // exit\n");
        aj.t("                    in(\"rdi\") code as u64,\n");
        aj.t("                    options(noreturn)\n");
        aj.t("                );\n");
        aj.t("            }\n");
        aj.t("        }\n");
        aj.t("    }\n");
        aj.t("}\n");
    }
    
    fn tcb(&self, aj: &mut String, f: &[u8]) {
        
        let message = self.sqi(f);
        
        aj.t("/// Transpiled: echo/print program\n");
        aj.t("/// Original syscall: write(1, message, len)\n\n");
        aj.t("use trustos_rt::prelude::*;\n\n");
        aj.t("#[no_mangle]\n");
        aj.t("pub extern \"C\" fn main(argc: i32, argv: *const *const u8) {\n");
        aj.t("    // Echo all arguments\n");
        aj.t("    for i in 1..argc {\n");
        aj.t("        let arg = unsafe { *argv.offset(i as isize) };\n");
        aj.t("        print_cstr(arg);\n");
        aj.t("        if i < argc - 1 {\n");
        aj.t("            print(\" \");\n");
        aj.t("        }\n");
        aj.t("    }\n");
        aj.t("    println(\"\");\n");
        aj.t("    sys_exit(0);\n");
        aj.t("}\n\n");
        
        if !message.is_empty() {
            aj.t(&format!("// Static message found: \"{}\"\n\n", message));
        }
        
        self.fjk(aj);
    }
    
    fn tcj(&self, aj: &mut String) {
        aj.t("/// Transpiled: pwd - print working directory\n");
        aj.t("/// Original syscall: getcwd(buf, size)\n\n");
        aj.t("use trustos_rt::prelude::*;\n\n");
        aj.t("#[no_mangle]\n");
        aj.t("pub extern \"C\" fn main() {\n");
        aj.t("    let cwd = sys_getcwd();\n");
        aj.t("    println(&cwd);\n");
        aj.t("    sys_exit(0);\n");
        aj.t("}\n\n");
        self.fjk(aj);
    }
    
    fn tcr(&self, aj: &mut String) {
        aj.t("/// Transpiled: uname - print system information\n");
        aj.t("/// Original syscall: uname(buf)\n\n");
        aj.t("use trustos_rt::prelude::*;\n\n");
        aj.t("#[no_mangle]\n");
        aj.t("pub extern \"C\" fn main() {\n");
        aj.t("    let info = sys_uname();\n");
        aj.t("    print(&info.sysname);\n");
        aj.t("    print(\" \");\n");
        aj.t("    print(&info.nodename);\n");
        aj.t("    print(\" \");\n");
        aj.t("    print(&info.release);\n");
        aj.t("    print(\" \");\n");
        aj.t("    print(&info.version);\n");
        aj.t("    print(\" \");\n");
        aj.t("    println(&info.machine);\n");
        aj.t("    sys_exit(0);\n");
        aj.t("}\n\n");
        self.fjk(aj);
    }
    
    fn tcf(&self, aj: &mut String) {
        aj.t("/// Transpiled: hostname\n\n");
        aj.t("use trustos_rt::prelude::*;\n\n");
        aj.t("#[no_mangle]\n");
        aj.t("pub extern \"C\" fn main() {\n");
        aj.t("    let info = sys_uname();\n");
        aj.t("    println(&info.nodename);\n");
        aj.t("    sys_exit(0);\n");
        aj.t("}\n\n");
        self.fjk(aj);
    }
    
    fn tbx(&self, aj: &mut String) {
        aj.t("/// Transpiled: cat - concatenate files\n\n");
        aj.t("use trustos_rt::prelude::*;\n\n");
        aj.t("#[no_mangle]\n");
        aj.t("pub extern \"C\" fn main(argc: i32, argv: *const *const u8) {\n");
        aj.t("    if argc < 2 {\n");
        aj.t("        // Read from stdin\n");
        aj.t("        let mut buf = [0u8; 4096];\n");
        aj.t("        loop {\n");
        aj.t("            let n = sys_read(0, &mut buf);\n");
        aj.t("            if n <= 0 { break; }\n");
        aj.t("            sys_write(1, &buf[..n as usize]);\n");
        aj.t("        }\n");
        aj.t("    } else {\n");
        aj.t("        for i in 1..argc {\n");
        aj.t("            let path = unsafe { cstr_to_str(*argv.offset(i as isize)) };\n");
        aj.t("            let fd = sys_open(&path, 0);\n");
        aj.t("            if fd >= 0 {\n");
        aj.t("                let mut buf = [0u8; 4096];\n");
        aj.t("                loop {\n");
        aj.t("                    let n = sys_read(fd, &mut buf);\n");
        aj.t("                    if n <= 0 { break; }\n");
        aj.t("                    sys_write(1, &buf[..n as usize]);\n");
        aj.t("                }\n");
        aj.t("                sys_close(fd);\n");
        aj.t("            }\n");
        aj.t("        }\n");
        aj.t("    }\n");
        aj.t("    sys_exit(0);\n");
        aj.t("}\n\n");
        self.fjk(aj);
    }
    
    fn tcg(&self, aj: &mut String) {
        aj.t("/// Transpiled: ls - list directory\n\n");
        aj.t("use trustos_rt::prelude::*;\n\n");
        aj.t("#[no_mangle]\n");
        aj.t("pub extern \"C\" fn main(argc: i32, argv: *const *const u8) {\n");
        aj.t("    let path = if argc > 1 {\n");
        aj.t("        unsafe { cstr_to_str(*argv.offset(1)) }\n");
        aj.t("    } else {\n");
        aj.t("        \".\"\n");
        aj.t("    };\n");
        aj.t("    \n");
        aj.t("    let entries = sys_readdir(path);\n");
        aj.t("    for entry in entries {\n");
        aj.t("        println(&entry);\n");
        aj.t("    }\n");
        aj.t("    sys_exit(0);\n");
        aj.t("}\n\n");
        self.fjk(aj);
    }
    
    fn tcd(&self, aj: &mut String) {
        aj.t("/// Transpiled: Generic binary\n");
        aj.t("/// Syscalls detected:\n");
        for jt in &self.apd {
            aj.t(&format!("///   - {} (0x{:x})\n", jt.j, jt.aqb));
        }
        aj.t("\n");
        aj.t("use trustos_rt::prelude::*;\n\n");
        aj.t("#[no_mangle]\n");
        aj.t("pub extern \"C\" fn main() {\n");
        
        
        for jt in &self.apd {
            match jt.j {
                "write" => {
                    let da = jt.n.get(0).hu().unwrap_or(1);
                    aj.t(&format!("    sys_write({}, b\"output\");\n", da));
                }
                "read" => {
                    let da = jt.n.get(0).hu().unwrap_or(0);
                    aj.t(&format!("    let mut buf = [0u8; 256];\n"));
                    aj.t(&format!("    sys_read({}, &mut buf);\n", da));
                }
                "exit" | "exit_group" => {
                    let status = jt.n.get(0).hu().unwrap_or(0) as i32;
                    aj.t(&format!("    sys_exit({});\n", status));
                }
                "getcwd" => {
                    aj.t("    let cwd = sys_getcwd();\n");
                    aj.t("    println(&cwd);\n");
                }
                "getpid" => {
                    aj.t("    let pid = sys_getpid();\n");
                }
                "open" | "openat" => {
                    aj.t("    let fd = sys_open(\"file\", 0);\n");
                }
                "close" => {
                    let da = jt.n.get(0).hu().unwrap_or(3) as i32;
                    aj.t(&format!("    sys_close({});\n", da));
                }
                _ => {
                    aj.t(&format!("    // TODO: {} syscall\n", jt.j));
                }
            }
        }
        
        
        if !self.apd.iter().any(|e| e.j == "exit" || e.j == "exit_group") {
            aj.t("    sys_exit(0);\n");
        }
        
        aj.t("}\n\n");
        self.fjk(aj);
    }
    
    fn fjk(&self, aj: &mut String) {
        aj.t("// TrustOS Runtime Library\n");
        aj.t("mod trustos_rt {\n");
        aj.t("    pub mod prelude {\n");
        aj.t("        pub use super::*;\n");
        aj.t("    }\n\n");
        
        aj.t("    pub struct UnameInfo {\n");
        aj.t("        pub sysname: &'static str,\n");
        aj.t("        pub nodename: &'static str,\n");
        aj.t("        pub release: &'static str,\n");
        aj.t("        pub version: &'static str,\n");
        aj.t("        pub machine: &'static str,\n");
        aj.t("    }\n\n");
        
        
        aj.t("    pub fn sys_exit(code: i32) -> ! {\n");
        aj.t("        unsafe {\n");
        aj.t("            core::arch::asm!(\n");
        aj.t("                \"syscall\",\n");
        aj.t("                in(\"rax\") 60u64,\n");
        aj.t("                in(\"rdi\") code as u64,\n");
        aj.t("                options(noreturn)\n");
        aj.t("            );\n");
        aj.t("        }\n");
        aj.t("    }\n\n");
        
        
        aj.t("    pub fn sys_write(fd: i32, buf: &[u8]) -> isize {\n");
        aj.t("        let ret: isize;\n");
        aj.t("        unsafe {\n");
        aj.t("            core::arch::asm!(\n");
        aj.t("                \"syscall\",\n");
        aj.t("                in(\"rax\") 1u64,\n");
        aj.t("                in(\"rdi\") fd as u64,\n");
        aj.t("                in(\"rsi\") buf.as_ptr(),\n");
        aj.t("                in(\"rdx\") buf.len(),\n");
        aj.t("                lateout(\"rax\") ret,\n");
        aj.t("            );\n");
        aj.t("        }\n");
        aj.t("        ret\n");
        aj.t("    }\n\n");
        
        
        aj.t("    pub fn sys_read(fd: i32, buf: &mut [u8]) -> isize {\n");
        aj.t("        let ret: isize;\n");
        aj.t("        unsafe {\n");
        aj.t("            core::arch::asm!(\n");
        aj.t("                \"syscall\",\n");
        aj.t("                in(\"rax\") 0u64,\n");
        aj.t("                in(\"rdi\") fd as u64,\n");
        aj.t("                in(\"rsi\") buf.as_mut_ptr(),\n");
        aj.t("                in(\"rdx\") buf.len(),\n");
        aj.t("                lateout(\"rax\") ret,\n");
        aj.t("            );\n");
        aj.t("        }\n");
        aj.t("        ret\n");
        aj.t("    }\n\n");
        
        
        aj.t("    pub fn sys_open(path: &str, flags: i32) -> i32 {\n");
        aj.t("        let ret: i64;\n");
        aj.t("        unsafe {\n");
        aj.t("            core::arch::asm!(\n");
        aj.t("                \"syscall\",\n");
        aj.t("                in(\"rax\") 2u64,\n");
        aj.t("                in(\"rdi\") path.as_ptr(),\n");
        aj.t("                in(\"rsi\") flags as u64,\n");
        aj.t("                lateout(\"rax\") ret,\n");
        aj.t("            );\n");
        aj.t("        }\n");
        aj.t("        ret as i32\n");
        aj.t("    }\n\n");
        
        
        aj.t("    pub fn sys_close(fd: i32) -> i32 {\n");
        aj.t("        let ret: i64;\n");
        aj.t("        unsafe {\n");
        aj.t("            core::arch::asm!(\n");
        aj.t("                \"syscall\",\n");
        aj.t("                in(\"rax\") 3u64,\n");
        aj.t("                in(\"rdi\") fd as u64,\n");
        aj.t("                lateout(\"rax\") ret,\n");
        aj.t("            );\n");
        aj.t("        }\n");
        aj.t("        ret as i32\n");
        aj.t("    }\n\n");
        
        
        aj.t("    pub fn sys_getcwd() -> &'static str {\n");
        aj.t("        // TrustOS implementation\n");
        aj.t("        \"/\"\n");
        aj.t("    }\n\n");
        
        
        aj.t("    pub fn sys_getpid() -> i32 {\n");
        aj.t("        let ret: i64;\n");
        aj.t("        unsafe {\n");
        aj.t("            core::arch::asm!(\n");
        aj.t("                \"syscall\",\n");
        aj.t("                in(\"rax\") 39u64,\n");
        aj.t("                lateout(\"rax\") ret,\n");
        aj.t("            );\n");
        aj.t("        }\n");
        aj.t("        ret as i32\n");
        aj.t("    }\n\n");
        
        
        aj.t("    pub fn sys_uname() -> UnameInfo {\n");
        aj.t("        UnameInfo {\n");
        aj.t("            sysname: \"TrustOS\",\n");
        aj.t("            nodename: \"trustos\",\n");
        aj.t("            release: \"1.0.0\",\n");
        aj.t("            version: \"#1 SMP Transpiled\",\n");
        aj.t("            machine: \"x86_64\",\n");
        aj.t("        }\n");
        aj.t("    }\n\n");
        
        
        aj.t("    pub fn sys_readdir(_path: &str) -> &'static [&'static str] {\n");
        aj.t("        &[\".\", \"..\"]\n");
        aj.t("    }\n\n");
        
        
        aj.t("    pub fn print(s: &str) {\n");
        aj.t("        sys_write(1, s.as_bytes());\n");
        aj.t("    }\n\n");
        
        aj.t("    pub fn println(s: &str) {\n");
        aj.t("        print(s);\n");
        aj.t("        sys_write(1, b\"\\n\");\n");
        aj.t("    }\n\n");
        
        aj.t("    pub fn print_cstr(s: *const u8) {\n");
        aj.t("        if s.is_null() { return; }\n");
        aj.t("        let mut len = 0;\n");
        aj.t("        unsafe {\n");
        aj.t("            while *s.offset(len) != 0 { len += 1; }\n");
        aj.t("            let slice = core::slice::from_raw_parts(s, len as usize);\n");
        aj.t("            sys_write(1, slice);\n");
        aj.t("        }\n");
        aj.t("    }\n\n");
        
        aj.t("    pub unsafe fn cstr_to_str(s: *const u8) -> &'static str {\n");
        aj.t("        if s.is_null() { return \"\"; }\n");
        aj.t("        let mut len = 0isize;\n");
        aj.t("        while *s.offset(len) != 0 { len += 1; }\n");
        aj.t("        let slice = core::slice::from_raw_parts(s, len as usize);\n");
        aj.t("        core::str::from_utf8_unchecked(slice)\n");
        aj.t("    }\n");
        
        aj.t("}\n");
    }
    
    fn sqi(&self, f: &[u8]) -> String {
        
        for jt in &self.apd {
            if jt.j == "write" && jt.n.len() >= 2 {
                let ag = jt.n[1];
                
                
            }
        }
        String::new()
    }
    
    
    pub fn nxk(&self) -> String {
        let mut an = String::new();
        an.t("; TrustOS Disassembly Listing\n");
        an.t("; Generated by Binary Transpiler\n\n");
        
        for fi in &self.instructions {
            
            an.t(&format!("{:016x}  ", fi.re));
            
            
            for o in &fi.bf {
                an.t(&format!("{:02x} ", o));
            }
            
            let nbc = fi.bf.len() * 3;
            if nbc < 16 {
                for _ in 0..(16 - nbc) {
                    an.push(' ');
                }
            }
            
            
            an.t(&fi.bes);
            if !fi.bvr.is_empty() {
                an.t("  ");
                for (a, op) in fi.bvr.iter().cf() {
                    if a > 0 { an.t(", "); }
                    match op {
                        Operand::Register(m) => an.t(m.j()),
                        Operand::Acf(p) => {
                            if *p >= 0 && *p < 256 {
                                an.t(&format!("{}", p));
                            } else {
                                an.t(&format!("0x{:x}", p));
                            }
                        }
                        Operand::Cy { ar, index, bv, aor } => {
                            an.push('[');
                            if let Some(o) = ar {
                                an.t(o.j());
                            }
                            if let Some(w) = index {
                                an.t("+");
                                an.t(w.j());
                                if *bv > 1 {
                                    an.t(&format!("*{}", bv));
                                }
                            }
                            if *aor != 0 {
                                if *aor > 0 {
                                    an.t(&format!("+0x{:x}", aor));
                                } else {
                                    an.t(&format!("-0x{:x}", -aor));
                                }
                            }
                            an.push(']');
                        }
                        Operand::Dy(dm) => an.t(dm),
                    }
                }
            }
            
            
            if let Some(r) = &fi.byv {
                an.t(&format!("  ; {}", r));
            }
            
            an.push('\n');
        }
        
        an
    }
}
